config/routes.rb
Rails.application.routes.draw do

  get 'information/brackets_2014' => 'information#brackets_2014'

  get 'information/seeds' => 'information#seeds'

  get 'information/about' => 'information#about'

  get 'information/teams_entered' => 'information#teams_entered'

  get 'information/schedule' => 'information#schedule'

  get 'information/entry_information' => 'information#entry_information'

  get 'information/map_to_msj' => 'information#map_to_msj'

  get 'information/place_winners_2014' => 'information#place_winners_2014'

  get 'information/hotels' => 'information#hotels'

  get 'information/results_prior_years' => 'information#results_prior_years'

  get 'public/MSJ_2015_Champions.pdf' => 'information#champions_1990_to_2013'

  get 'wrestlers/sort_by_school' => 'wrestlers#sort_by_school'

  get 'wrestlers/sort_by_state_place' => 'wrestlers#sort_by_state_place'

  get 'users/home' => 'users#home'

  get 'users/send' => 'users#send', as: :send_welcome_mail

  # get 'users/wrestlers/no_entry' => 'users/wrestlers/#no_entry', as: :no_entry

  post 'create_user' => 'users#create', as: :create_user

  devise_for :users
  root 'welcome#index'


  resources :users, except: :create do
    resources :wrestlers, controller: "users/wrestlers"

  end

  resources :teams, only: [:index]

  resources :tournaments, only: [:index, :edit, :update]

  resources :wrestlers, only: [:index, :edit, :show, :update]

  controller :tournaments do
    delete '/tournaments/:id',      action: 'destroy'
  end

  controller :wrestlers do
    delete '/wrestlers/:id',      action: 'destroy'
  end

  controller :users do
    delete '/users/:id',      action: 'destroy'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :timeout_in => 24.hours

  has_many :wrestlers

  validates :name, presence: true


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/wrestler.rb
class Wrestler < ActiveRecord::Base

  belongs_to :user

  validates :first_name, presence: true, null: false
  validates :last_name, presence: true, null: false
  validates :weight, presence: true, null: false
  validates :wins, presence: true, null: false
  validates :losses, presence: true, null: false
  validates_uniqueness_of :league_place, scope: [:weight, :league]
  validates_uniqueness_of :school, scope: :weight


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["weight", "league place", "last name", "first name", "grade", "school", "wins", "losses", "league", "abbreviation", "seed"]
      all.each do |wrestler|
        csv << [wrestler.weight, wrestler.league_place, wrestler.last_name, wrestler.first_name, wrestler.grade, wrestler.school, wrestler.wins, wrestler.losses, wrestler.league, wrestler.abbreviation, wrestler.seed]
      end
    end
  end
end

app/controllers/teams/wrestlers_controller.rb
module Teams
  class WrestlersController < ApplicationController

    def index
      user = User.find_by_id(session[:user_id])
      @teams = Team.order('name ASC')
      @team = Team.find(params[:team_id])
      wrestlers = @team.wrestlers.order('weight ASC') # specifically for csv
      @wrestlers = @team.wrestlers.order('weight ASC') # for index
      @wrestler = @team.wrestlers.new
      respond_to do |format|
        format.html
        format.csv { send_data wrestlers.to_csv }
        format.xls { send_data wrestlers.to_csv(col_sep: "\t")}
      end
    end

    def new
      @team = Team.find(params[:team_id])
      @wrestler = @team.wrestlers.new
    end

    def create
      @team = Team.find(params[:team_id])
      @wrestler = @team.wrestlers.new(wrestler_params)
      @wrestler.school = @team.name

      respond_to do |format|
        if @wrestler.save
          format.html { redirect_to team_wrestlers_path, notice: 'wrestler was successfully created.' }
          format.json { render action: 'index', status: :created, location: @wrestler }
          # added:
          format.js   { render action: 'index', status: :created, location: @wrestler }
        else
          format.html { render action: 'new' }
          format.json { render json: @wrestler.errors, status: :unprocessable_entity }
          # added:
          format.js   { render json: @wrestler.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
      @team = Team.find(params[:team_id])
      @wrestler = @team.wrestlers.find(params[:id])
    end

    def show
      @teams = Team.order('name ASC')
      @team = Team.find(params[:team_id])
      @wrestler = @team.wrestlers.find(params[:id])
    end

    def update
      @wrestlers = Wrestler.order('weight ASC')
      @wrestler = Wrestler.find(params[:id])

      if @wrestler.update(wrestler_params)
        redirect_to @wrestler.team
      else
        render :edit
      end
    end

    def destroy
      @wrestler = wrestler.find_by_id(params[:id])
      @wrestler.destroy
      redirect_to wrestlers_path
    end


    private

    def wrestler_params
      params.require(:wrestler).permit(:school, :first_name, :last_name, :weight, :grade, :wins, :losses, :section_place, :state_place, :tourney1_place, :tourney2_place, :tourney3_place, :tourney4_place, :tourney5_place, :tourney6_place, :tourney7_place, :tourney8_place, :comments, :team_id)
    end
  end
end

app/controllers/users/wrestlers_controller.rb
module Users
  class WrestlersController < ApplicationController

    def index
      @number = 1
      user = User.find(params[:user_id])

      @user = User.find(params[:user_id])
      wrestlers = @user.wrestlers.order('weight ASC, league_place ASC') # specifically for csv
      @wrestlers = @user.wrestlers.order('weight ASC, league_place ASC') # for index
      @wrestler = @user.wrestlers.new

      respond_to do |format|
        format.html
        format.csv { send_data wrestlers.to_csv, filename: user.league + '.csv' }
        format.xls { send_data wrestlers.to_csv(col_sep: "\t"), filename: user.league + '.xls' }

      end
    end

    def new
      @user = User.find(params[:user_id])
      @wrestler = @user.wrestlers.new

    end

    def create
      @user = User.find(params[:user_id])

      @wrestler = @user.wrestlers.new(wrestler_params)
      @wrestler.league = @user.league


      user = current_user

      respond_to do |format|
        if @wrestler.save
          UserMailer.wrestler_added(user).deliver
          format.html { redirect_to user_wrestlers_path, notice: 'wrestler was successfully created.' }
          format.json { render action: 'index', status: :created, location: @wrestler }
          # added:
          format.js   { render action: 'index', status: :created, location: @wrestler }
        else
          format.html { render action: 'new' }
          format.json { render json: @wrestler.errors, status: :unprocessable_entity }
          # added:
          format.js   { render json: @wrestler.errors, status: :unprocessable_entity }
        end
      end

    end

    def edit
      @user = User.find(params[:user_id])
      @wrestler = @user.wrestlers.find(params[:id])
    end

    def show
      @teams = Team.order('name ASC')
      @wrestler = @team.wrestlers.find(params[:id])
    end

    def update
      @wrestlers = Wrestler.order('weight ASC')
      @wrestler = Wrestler.find(params[:id])

      if @wrestler.update(wrestler_params)

        redirect_to users_home_path(current_user)
      else
        render :edit
      end
    end

    def destroy
      user = current_user
      @wrestler = wrestler.find_by_id(params[:id])
      @wrestler.destroy
      UserMailer.wrestler_deleted(user).deliver
      redirect_to wrestlers_path
    end


    private

    def wrestler_params
      params.require(:wrestler).permit(:school, :first_name, :last_name, :weight, :grade, :wins, :losses, :league_place,  :comments, :seed, :user_id)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_admin, only: :create

  before_filter :skip_password_attribute, :only => [:edit, :update]

  def home
    @user = current_user
    @wrestlers = @user.wrestlers.order('weight ASC')
    @wrestler = @user.wrestlers.new

  end

  # def send
  #   @users = User.all
  #   @users.each do |user|
  #     UserMailer.new_user(user).deliver
  #   end
  #     redirect_to root_url
  # end



  def index
    @users = User.order('league Asc')
    users = User.order('league Asc')
    respond_to do |format|
      format.html
      format.csv { send_data users.to_csv }
      format.xls { send_data users.to_csv(col_sep: "\t")}
    end
  end

  def new
    @user = User.new
    @teams = Team.all
    @list = ['C', 'CC', 'LA', 'N', 'NC', 'O', 'S', 'SD', 'SF', 'SJ', 'OTHER SCHOOLIO']
  end

  def edit

    @user = User.find(params[:id])
  end

  def update
    @users = User.order('name ASC')
    @user = User.find(params[:id])
    if @user.update(user_params)
      if current_user.admin?
        redirect_to users_path
      else
        redirect_to user_wrestlers_path(@user)
      end
    else
      render :edit
    end
  end

  def create
     @user = User.create(user_params)
    if @user.persisted?
      # @team = Team.new
      # @team.school = @user.school
      # @team.user_id = @user.id
      # @team = Team.create(team_params)
      UserMailer.new_user(@user).deliver
      redirect_to root_url, notice: "User was successfully created"
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @users = User.order('name ASC')
    @user = User.find_by_id(params[:id])
    # @tournaments = @user.tournaments.all
    # @wrestlers = @user.wrestlers.all
    # @wrestlers.destroy
    # @tournaments.destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def skip_password_attribute
    if params[:password].blank? && params[:password_validation].blank?
      params.except!(:password, :password_validation)
    end
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :cell, :league)
  end

end

app/controllers/wrestlers_controller.rb
class WrestlersController < ApplicationController
  respond_to  :html, :js

  def index

    @wrestlers = Wrestler.order('weight ASC, league_place ASC')
    wrestlers = Wrestler.order('weight ASC, league_place ASC')  # for csv format


    respond_to do |format|
      format.html
      format.csv { send_data wrestlers.to_csv }
      format.xls { send_data wrestlers.to_csv(col_sep: "\t")}

    end
  end



  def new
    @team = Team.find(params[:id])
    @wrestler = @team.wrestlers.new
  end

  def create

    @wrestler = team.wrestlers.create(wrestler_params)
    user = current_user

    respond_to do |format|
      if @wrestler.save
        UserMailer.wrestler_added(user).deliver
        format.html { redirect_to team_path, notice: 'wrestler was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wrestler }
        # added:
        format.js   { render action: 'show', status: :created, location: @wrestler }
      else
        format.html { render action: 'new' }
        format.json { render json: @wrestler.errors, status: :unprocessable_entity }
        # added:
        format.js   { render json: @wrestler.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @wrestler = Wrestler.find(params[:id])

  end

  def show
    @wrestler = Wrestler.find(params[:id])
  end

  def update
    @wrestler = Wrestler.find(params[:id])

    user = current_user
    if @wrestler.update(wrestler_params)
     # UserMailer.wrestler_updated(user).deliver
      if current_user.admin?
        redirect_to wrestlers_path
      else
        redirect_to user_wrestlers_path(user)
      end
    else
      render :edit
    end
  end

  def destroy
    user = current_user
    @wrestler = Wrestler.find(params[:id])
    @wrestler.destroy
    UserMailer.wrestler_deleted(user).deliver
    redirect_to user_wrestlers_path(user)
  end

  private

  def wrestler_params
    params.require(:wrestler).permit(:school, :first_name, :last_name, :weight, :grade, :wins, :losses, :league_place, :comments, :seed, :user_id)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wrestlers_helper.rb
module WrestlersHelper
end

app/views/users/wrestlers/_form.html.erb
<br><br>
<div class="border-wrestler-div">
  <% modal ||= false %>
  <% remote = modal ? true : false %>
    <%= form_for([@user, @wrestler], remote: remote, html: { role: :form, 'data-model' => 'wrestler'}) do |f| %>
      <% if @wrestler.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@wrestler.errors.count, "error") %> prohibited this wrestler from being saved:</h2>

          <ul>
          <% @wrestler.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
          <div class="form-group">
            <%= f.label :weight, class: 'col-sm-2 control-label' %>
            <div class="col-sm-4">
                <%= f.collection_select :weight, ['106', '113', '120', '126', '132', '138', '145', '152', '160', '170', '182', '195', '220', '285'], :to_s, :to_s, :include_blank => true %>
            </div>

            <%= f.label :league_place, "League Place", class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.collection_select :league_place, ['1', '2', '3', '4/Alt 1', '5/Alt 2'], :to_s, :to_s, :include_blank => true%>
          </div>
            <br><br>
          </div>
        </div>

      <div class="row">
        <div class="form-group">
          <%= f.label :first, class: 'col-sm-2 control-label' %>
            <div class="col-sm-4">
              <%= f.text_field :first_name, class: 'form-control' %><br>
            </div>
          <%= f.label :last, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.text_field :last_name, class: 'form-control' %><br>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label :school, class: 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <% if @user.league == "BAC" %>
              <%= f.collection_select :school, ['Athenian', 'Ca Schl Deaf', 'John Swett', 'Lick-Wilmerding', 'Liv Vly Charter', 'St. Pat - St. Vin', 'Stuart Hall'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "BVAL" %>
              <%= f.collection_select :school, ['Antioch', 'Deer Valley', 'Freedom', 'Heritage', 'Liberty', 'Pittsburg'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "CMC" %>
              <%= f.collection_select :school, ['Archbishop Hanna', 'Clear Lake', 'Fort Bragg', 'Kelseyville', 'Lower Lake', 'Middletown', 'Point Arena', 'St. Helena', 'Technology', 'Upper Lake', 'Willits'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "DFAL" %>
              <%= f.collection_select :school, ['Acalanes', 'Alhambra', 'Campolindo', 'Dougherty Valley', 'Dublin', 'Las Lomas', 'Miramonte'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "DVAL" %>
              <%= f.collection_select :school, ['Berean Christian', 'Clayton Valley', 'College Park', 'Concord', 'Mt. Diablo', 'Northgate', 'Ygnacio Valley'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "EBAL" %>
              <%= f.collection_select :school, ['Amador Valley', 'California', 'De La Salle', 'Foothill', 'Granada', 'Livermore', 'Monte Vista', 'San Ramon'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "HDNL" %>
              <%= f.collection_select :school, ['Arcata', 'Del Norte', 'Eureka', 'Fortuna', 'Hoopa', 'McKinleyville', 'South Fork'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "MCAL" %>
              <%= f.collection_select :school, ['Justin Sienna', 'Marin Catholic', 'Novato', 'Redwood', 'San Marin', 'San Rafael', 'Sir Francis Drake', 'Tamalpais', 'Terra Linda'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "MVAL" %>
              <%= f.collection_select :school, ['American', 'Irvington', 'J F Kennedy', 'James Logan', 'Mission San Jose', 'Newark Memorial', 'Washington'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "NBL" %>
              <%= f.collection_select :school, ['Cardinal Newman', 'Casa Grande', 'Maria Carrillo', 'Montgoery', 'Rancho Cotate', 'Santa Rosa', 'Ukiah', 'Windsor'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "SCL" %>
              <%= f.collection_select :school, ['Analy', 'El Molino', 'Elsie Allen', 'Healdsburg', 'Petaluma', 'Piner', 'Sonoma Valley'], :to_s, :to_s, :include_blank => true%>
            <% elsif @user.league == "WACC" %>
              <%= f.collection_select :school, ['Albany', 'Arroyo', 'Berkeley', 'Castro Valley', 'Hayward', 'Mt. Eden', 'San Leandro', 'San Lorenzo'], :to_s, :to_s, :include_blank => true%>
            <% end %>
          </div>
        </div><br>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label :grade, "Grade (9-12)", class: 'col-sm-2 control-label' %>
            <div class="col-sm-4">
              <%= f.collection_select :grade, ['9', '10', '11', '12'], :to_s, :to_s %>
            </div>
          <%= f.label :wins, "W (Req)", class: 'col-sm-1 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :wins, class: 'form-control' %>
          </div>
          <%= f.label :losses, "L (Req)", class: 'col-sm-1 control-label' %>
          <div class="col-sm-2">
            <%= f.text_field :losses, class: 'form-control' %><br>
          </div>
        </div>
      </div>

      <% if current_user.admin? %>
        <div class="row">
          <div class="form-group">
            <%= f.label :seed, class: 'col-sm-2 control-label' %>
              <div class="col-sm-4">
                <%= f.collection_select :seed, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'], :to_s, :to_s, :include_blank => true %>
              </div>
          </div>
        </div><br>
      <% end %>


      <div class="form-actions">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      </div><br>
      If the form doesn't save, check to make sure you don't have a duplicate weight and league place already entered!  If you did attempt to enter a duplicate, close the form and click add wrestler button again.  <br><br>
    <% end %>
  </div>
</div>

app/views/users/wrestlers/_index.html.erb
<div class="team-name">

  <h1>Wrestlers</h1>
 <% if current_user.admin? %> |
  <p>
 ***  <%= link_to "NO ENTRY FILL", no_entry_path(@user) %> ***
    Sort by:
      <%= link_to "School", wrestlers_sort_by_school_path %> |
      <%= link_to "Weight", wrestlers_path %> |
      <%= link_to "State Place", wrestlers_sort_by_state_place_path %>
  </p>

  <p>
    Download:
      <%= link_to "CSV", wrestlers_path(format: "csv") %> |
      <%= link_to "Excel", wrestlers_path(format: "xls") %> |
      <% end %>
      <% if current_user.admin? || current_user.id == @user.id %>

        <%= link_to 'ADD WRESTLER', '#new_user_wrestler_modal', 'data-toggle' => 'modal' %>
      <% end %>

  </p>

</div>

</div>
<div class="container" ng-view="">
  <div class="row">
    <div class="panel ">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="wrestlers_table">
            <thead>
              <tr>
                <th>Wt</th>
                <th>School</th>
                <th>First</th>
                <th>Last</th>
                <th>YR</th>
                <th>W</th>
                <th>L</th>
                <th>League Place</th>


                  <th>Comments</th>
                   <% if current_user.admin? || current_user.id == @user.id %>
                  <th class="col-md-0">Edit Wrestler</th>
                  <th class="col-md-0">Delete Wrestler</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @wrestlers.each do |wrestler, user| %>
                <%= render partial: '/users/wrestlers/table_row', locals: { wrestler: wrestler, user: user} %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="add_wrestler_button">
      <% if current_user.admin? || current_user.id == @user.id %>
        <h3><button type="button" class="btn-large btn-default"><%= link_to 'ADD WRESTLER', '#new_user_wrestler_modal', 'data-toggle' => 'modal' %></button></h3><br><br><br>
      <% end %>
    </div>
  <div class="modal fade" id="new_user_wrestler_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add Wrestler</h4>
        </div>
        <div class="modal-body">
          <%= render 'users/wrestlers/form', modal: true %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/wrestlers/_table_row.html.erb
<tr>
  <td><%= wrestler.seed %> <% if wrestler.seed.to_s != "" %>seed<% end %></td>

  <td><%= wrestler.weight %></td>
  <td><%= wrestler.league_place %></td>
  <td><%= wrestler.league %></td>
  <td><%= wrestler.school %></td>
  <td><%= wrestler.first_name %></td>
  <td><%= wrestler.last_name %></td>
  <td><%= wrestler.grade %></td>
  <td><%= wrestler.wins %></td>
  <td><%= wrestler.losses %></td>



  <% if current_user.admin?  %>
    <td><%= link_to 'Edit', edit_wrestler_path(wrestler) %></td>
    <td><%= link_to 'Delete', wrestler, method: "delete", :data => {:confirm => 'Are you sure?'} %></td>
  <% end %>
  </td>
</tr>

app/views/users/wrestlers/create.js.erb
$('#wrestlers').html("<%= j (render @wrestlers) %>");
$('#wrestler-form').slideUp(350);

app/views/users/wrestlers/edit.html.erb
<br><br><br><br><br><br>
<%= render 'wrestlers/form', { :wrestler => @wrestler } %>

app/views/users/wrestlers/index.csv.erb
<%- headers = ['Weight', 'School', 'Abbreviation', 'Last', 'First', 'Grade', 'Wins', 'Losses'] -%>
<%= CSV.generate_line headers %>
<%- @wrestlers.each do |wrestler| -%>
  <%= CSV.generate_line([wrestler.weight, wrestler.school, wrestler.abbreviation, wrestler.last_name, wrestler.first_name, wrestler.grade, wrestler.wins, wrestler.losses]) %>
<%- end -%>

app/views/users/wrestlers/index.html.erb
<div class="team-name">
  <h2><%= @user.league.upcase %></h2>
</div>
<div class="container-team" ng-view="">
  <div class="row">
    <div class="panel">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="teams_table">
            <thead>
              <tr>
                <th class="col-md-1">League</th>
                <th class="col-md-1">League Rep</th>

                <% if current_user.admin? %>
                <th class="col-md-1">Cell</th>
                <th class="col-md-1">Email</th>
                <th class="col-md-1">Edit Team Info</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
                <%= render partial: '/users/table_row2', locals: { user: @user} %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="team-name">






  <h3>WRESTLERS</h3>

    Download:
      <%= link_to "CSV", user_wrestlers_path(format: "csv") %> |
      <%= link_to "Excel", user_wrestlers_path(format: "xls") %>
      <% if current_user.admin?  %> |

        <%= link_to 'ADD WRESTLER', '#new_user_wrestler_modal', 'data-toggle' => 'modal' %>
      <% end %>
  </p>
</div>
<div class="container" ng-view="">
<div class="row">
    <div class="panel ">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="wrestlers_table">
            <thead>
              <tr>
                <th></th>
                <th>Wt</th>
                <th>League Place</th>
                <th>League</th>
                <th>School</th>
                <th>First</th>
                <th>Last</th>
                <th>YR</th>
                <th>W</th>
                <th>L</th>

                  <% if current_user.admin? %>
                  <th class="col-md-0">Edit Wrestler</th>
                  <th class="col-md-0">Delete Wrestler</th>
                <% end %>

              </tr>
            </thead>

            <tbody>

              <% @wrestlers.each do |wrestler, user| %>
                <%= render partial: '/users/wrestlers/table_row', locals: { wrestler: wrestler, user: user} %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<div class="add_wrestler_button">
  <% if current_user.admin?  %>
    <h3><%= link_to 'ADD WRESTLER', '#new_user_wrestler_modal', 'data-toggle' => 'modal' %></h3><br><br><br>
  <% end %>
</div>
<div class="modal fade" id="new_user_wrestler_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add Wrestler</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="edit_wrestler_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Wrestler</h4>
      </div>
      <div class="modal-body">
        <%= render 'wrestlers/form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

</div>

app/views/users/wrestlers/new.js.erb
$('#wrestler-form').html("<%= j (render 'form') %>");
$('#wrestler-form').slideDown(350);

app/views/users/wrestlers/show.js.erb
$('#wrestlers_table').append("<%= j render partial: 'table_row', locals: {wrestler: @wrestler } %>");
$('#new_wrestler_modal').modal_success();