config/routes.rb
Rails.application.routes.draw do

  get 'information/brackets_2014' => 'information#brackets_2014'

  get 'information/seeds' => 'information#seeds'

  get 'information/about' => 'information#about'

  get 'information/teams_entered' => 'information#teams_entered'

  get 'information/schedule' => 'information#schedule'

  get 'information/entry_information' => 'information#entry_information'

  get 'information/map_to_msj' => 'information#map_to_msj'

  get 'information/place_winners_2014' => 'information#place_winners_2014'

  get 'information/hotels' => 'information#hotels'

  get 'information/results_prior_years' => 'information#results_prior_years'

  get 'public/MSJ_2015_Champions.pdf' => 'information#champions_1990_to_2013'

  get 'wrestlers/sort_by_school' => 'wrestlers#sort_by_school'

  get 'wrestlers/sort_by_state_place' => 'wrestlers#sort_by_state_place'

  get 'users/home' => 'users#home'

  get 'users/send' => 'users#send', as: :send_welcome_mail

  # get 'users/wrestlers/no_entry' => 'users/wrestlers/#no_entry', as: :no_entry

  post 'create_user' => 'users#create', as: :create_user

  devise_for :users
  root 'welcome#index'


  resources :users, except: :create do
    resources :wrestlers, controller: "users/wrestlers"

  end

  resources :teams, only: [:index]

  resources :tournaments, only: [:index, :edit, :update]

  resources :wrestlers, only: [:index, :edit, :show, :update]

  controller :tournaments do
    delete '/tournaments/:id',      action: 'destroy'
  end

  controller :wrestlers do
    delete '/wrestlers/:id',      action: 'destroy'
  end

  controller :users do
    delete '/users/:id',      action: 'destroy'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :timeout_in => 24.hours

  has_many :wrestlers

  validates :name, presence: true


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/users/wrestlers_controller.rb
module Users
  class WrestlersController < ApplicationController

    def index
      @number = 1
      user = User.find(params[:user_id])

      @user = User.find(params[:user_id])
      wrestlers = @user.wrestlers.order('weight ASC, league_place ASC') # specifically for csv
      @wrestlers = @user.wrestlers.order('weight ASC, league_place ASC') # for index
      @wrestler = @user.wrestlers.new

      respond_to do |format|
        format.html
        format.csv { send_data wrestlers.to_csv, filename: user.league + '.csv' }
        format.xls { send_data wrestlers.to_csv(col_sep: "\t"), filename: user.league + '.xls' }

      end
    end

    def new
      @user = User.find(params[:user_id])
      @wrestler = @user.wrestlers.new

    end

    def create
      @user = User.find(params[:user_id])

      @wrestler = @user.wrestlers.new(wrestler_params)
      @wrestler.league = @user.league


      user = current_user

      respond_to do |format|
        if @wrestler.save
          UserMailer.wrestler_added(user).deliver
          format.html { redirect_to user_wrestlers_path, notice: 'wrestler was successfully created.' }
          format.json { render action: 'index', status: :created, location: @wrestler }
          # added:
          format.js   { render action: 'index', status: :created, location: @wrestler }
        else
          format.html { render action: 'new' }
          format.json { render json: @wrestler.errors, status: :unprocessable_entity }
          # added:
          format.js   { render json: @wrestler.errors, status: :unprocessable_entity }
        end
      end

    end

    def edit
      @user = User.find(params[:user_id])
      @wrestler = @user.wrestlers.find(params[:id])
    end

    def show
      @teams = Team.order('name ASC')
      @wrestler = @team.wrestlers.find(params[:id])
    end

    def update
      @wrestlers = Wrestler.order('weight ASC')
      @wrestler = Wrestler.find(params[:id])

      if @wrestler.update(wrestler_params)

        redirect_to users_home_path(current_user)
      else
        render :edit
      end
    end

    def destroy
      user = current_user
      @wrestler = wrestler.find_by_id(params[:id])
      @wrestler.destroy
      UserMailer.wrestler_deleted(user).deliver
      redirect_to wrestlers_path
    end


    private

    def wrestler_params
      params.require(:wrestler).permit(:school, :first_name, :last_name, :weight, :grade, :wins, :losses, :league_place,  :comments, :seed, :user_id)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_admin, only: :create

  before_filter :skip_password_attribute, :only => [:edit, :update]

  def home
    @user = current_user
    @wrestlers = @user.wrestlers.order('weight ASC')
    @wrestler = @user.wrestlers.new

  end

  # def send
  #   @users = User.all
  #   @users.each do |user|
  #     UserMailer.new_user(user).deliver
  #   end
  #     redirect_to root_url
  # end



  def index
    @users = User.order('league Asc')
    users = User.order('league Asc')
    respond_to do |format|
      format.html
      format.csv { send_data users.to_csv }
      format.xls { send_data users.to_csv(col_sep: "\t")}
    end
  end

  def new
    @user = User.new
    @teams = Team.all
    @list = ['C', 'CC', 'LA', 'N', 'NC', 'O', 'S', 'SD', 'SF', 'SJ', 'OTHER SCHOOLIO']
  end

  def edit

    @user = User.find(params[:id])
  end

  def update
    @users = User.order('name ASC')
    @user = User.find(params[:id])
    if @user.update(user_params)
      if current_user.admin?
        redirect_to users_path
      else
        redirect_to user_wrestlers_path(@user)
      end
    else
      render :edit
    end
  end

  def create
     @user = User.create(user_params)
    if @user.persisted?
      # @team = Team.new
      # @team.school = @user.school
      # @team.user_id = @user.id
      # @team = Team.create(team_params)
      UserMailer.new_user(@user).deliver
      redirect_to root_url, notice: "User was successfully created"
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @users = User.order('name ASC')
    @user = User.find_by_id(params[:id])
    # @tournaments = @user.tournaments.all
    # @wrestlers = @user.wrestlers.all
    # @wrestlers.destroy
    # @tournaments.destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def skip_password_attribute
    if params[:password].blank? && params[:password_validation].blank?
      params.except!(:password, :password_validation)
    end
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :cell, :league)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user_form.html.erb
<div class="border-form-div">

  <h3>Edit Team log in & contact information</h3>

  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email, "Email (username)" %><br>
      <%= f.text_field :email, :readonly => true %>
    </div>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :league %><br>
      <%= f.collection_select :league, ['BAC', 'BVAL', 'CMC', 'DFAL', 'DVAL', 'EBAL', 'HDNL', 'MCAL', 'MVAL', 'NBL', 'SCL', 'WACC'], :to_s, :to_s, :include_blank => true %>
    </div><br>

    <div class="field">
      <%= f.label :cell, "Phone #" %><br>
      <%= f.text_field :cell %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/_signup_form.html.erb
<div class="border-form-div">

  <h2>Create New User</h2>

  <%= form_for User.new, url: create_user_path  do |f| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :league %><br>
      <%= f.collection_select :league, ['BAC', 'BVAL', 'CMC', 'DFAL', 'DVAL', 'EBAL', 'HDNL', 'MCAL', 'MVAL', 'NBL', 'SCL', 'WACC'], :to_s, :to_s, :include_blank => true %>
    </div><br>

    <div class="field">
      <%= f.label :cell, "Phone #" %><br>
      <%= f.text_field :cell %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/_table_row.html.erb
<tr>
  <td><%= user.league %></td>
  <td><%= user.name %></td>

    <td><%= link_to "Wrestlers (#{user.wrestlers.count})", user_wrestlers_path(user) %></td>
    <% if current_user.admin? %>
    <td><%= user.cell %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user)%></td>
    <td><%= link_to 'Delete', user, method: "delete", :data => {:confirm => 'Are you sure?'} %>

    <% end %>

  </td>
</tr>

app/views/users/_table_row2.html.erb
<tr>
  <td><%= user.league %></td>
  <td><%= user.name %></td>



    <% if current_user.admin? %>
    <td><%= user.cell %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user)%></td>
    <% end %>

  </td>
</tr>

app/views/users/edit.html.erb
<%= render partial: 'edit_user_form', locals: { user: @user } %>

app/views/users/home.html.erb
<div class="team-name">
  <h3><%= @user.school.upcase %></h3>
</div>
<div class="container-team" ng-view="">
  <div class="row">
    <div class="panel">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover" id="teams_table">
            <thead>
              <tr>
                <th class="col-md-1">Team Name</th>
                <th class="col-md-1">Section</th>
                <th class="col-md-1">Coach</th>
                <th class="col-md-1">Cell</th>
                <th class="col-md-1">Email</th>
                <th class="col-md-1">Edit Team Info</th>
              </tr>
            </thead>
            <tbody>
                <%= render partial: '/users/table_row', locals: { user: @user} %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'users/tournaments/index', locals: { user: @user, tournaments: @tournaments } %>

<%= render partial: 'users/wrestlers/index', locals: { wrestlers: @wrestlers} %>
<br>

app/views/users/index.html.erb
<div class="team-name">
  <h3>LEAGUES ENTERED</h3>


</div>
<div class="container" ng-view="">
  <div class="row">
    <div class="panel">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover ">
            <thead>
              <tr>
               <th class="col-md-1">League</th>
                <th class="col-md-1">League Rep</th>
                <th class="col-md-1">Section Qualifiers / Alternates</th>
               </th>
                <% if current_user.admin? %>
                  <th class="col-md-1">Cell</th>
                  <th class="col-md-1">Email</th>
                  <th class="col-md-1">Edit User Info</th>
                  <th class="col-md-1">Delete</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <% if current_user.admin? || user.league != "" %>
                  <%= render partial: 'users/table_row', locals: { user: user } %>

                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <table>
      <Row>
        <Cell><Data ss:Type="String">School</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Coach</Data></Cell>
        <Cell><Data ss:Type="String">Cell</Data></Cell>
      </Row>
      <% @users.each do |user| %>
        <Row>
          <Cell><Data ss:Type="String"><%= user.abbreviation %></Data></Cell>
          <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
          <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= user.cell %></Data></Cell>
        </Row>
      <% end %>
    </table>
  </Worksheet>
</Workbook>

app/views/users/new.html.erb
<%= render partial: 'signup_form', locals: { user: @user} %>