config/routes.rb
Rails.application.routes.draw do

  get 'information/brackets_2014' => 'information#brackets_2014'

  get 'information/seeds' => 'information#seeds'

  get 'information/about' => 'information#about'

  get 'information/teams_entered' => 'information#teams_entered'

  get 'information/schedule' => 'information#schedule'

  get 'information/entry_information' => 'information#entry_information'

  get 'information/map_to_msj' => 'information#map_to_msj'

  get 'information/place_winners_2014' => 'information#place_winners_2014'

  get 'information/hotels' => 'information#hotels'

  get 'information/results_prior_years' => 'information#results_prior_years'

  get 'public/MSJ_2015_Champions.pdf' => 'information#champions_1990_to_2013'

  get 'wrestlers/sort_by_school' => 'wrestlers#sort_by_school'

  get 'wrestlers/sort_by_state_place' => 'wrestlers#sort_by_state_place'

  get 'users/home' => 'users#home'

  get 'users/send' => 'users#send', as: :send_welcome_mail

  # get 'users/wrestlers/no_entry' => 'users/wrestlers/#no_entry', as: :no_entry

  post 'create_user' => 'users#create', as: :create_user

  devise_for :users
  root 'welcome#index'


  resources :users, except: :create do
    resources :wrestlers, controller: "users/wrestlers"

  end

  resources :teams, only: [:index]

  resources :tournaments, only: [:index, :edit, :update]

  resources :wrestlers, only: [:index, :edit, :show, :update]

  controller :tournaments do
    delete '/tournaments/:id',      action: 'destroy'
  end

  controller :wrestlers do
    delete '/wrestlers/:id',      action: 'destroy'
  end

  controller :users do
    delete '/users/:id',      action: 'destroy'
  end

end

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom hidden-xs hidden-sm" role="navigation">
  <div class="row">
    <div class="col-lg-3">
      <a><%= link_to '2015 SEEDS  ', information_seeds_path %></a>
    </div>
    <div class="col-lg-3">
      <a><%= link_to '2015 SCHEDULE  ', "http://cifncs.org/sports/wrestling/files/2015%20NCS%20Schedule%20-%20Semis%202%20Mat.pdf" %></a>
    </div>
    <div class="col-lg-3">

      <a><%= link_to '2014 BRACKETS', asset_path("2014brackets.pdf"), :class => "links" %></a>
    </div>
    <div class="col-lg-3">

      <a><%= link_to 'PAST RESULTS', "http://cifncs.org/sports/wrestling/files/Results/MasterResultsPage.htm" %></a>
    </div>
  </div>
  <div class="ncs-brackets">
    hosted by JAMES LOGAN HIGH SCHOOL, Union City
  </div>

  <div class="container">

    <div id="nav">
    </div>
  </div>
</nav>

<nav class="navbar navbar-default navbar-fixed-bottom visible-xs visible-sm" role="navigation">

  <div class="row">
    <div class="col-xs-3 ">
      <a><%= link_to 'SEEDS  ', information_seeds_path %></a>
    </div>
    <div class="col-xs-3 ">
      <a><%= link_to 'SCHEDULE  ', "http://cifncs.org/sports/wrestling/files/2015%20NCS%20Schedule%20-%20Semis%202%20Mat.pdf" %></a>
    </div>
    <div class="col-xs-3 ">

      <a><%= link_to '2014 RESULTS', asset_path("2014brackets.pdf"), :class => "links" %></a>
    </div>
    <div class="col-xs-3 ">

      <a><%= link_to 'PAST RESULTS', "http://cifncs.org/sports/wrestling/files/Results/MasterResultsPage.htm" %></a>
    </div>

  </div>

  <div class="ncs-brackets-footer">
    hosted by JAMES LOGAN HIGH SCHOOL
  </div>
  <div class="container">
    <div id="nav">
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
 <nav class="navbar navbar-default navbar-fixed-top hidden-xs hidden-sm " role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 vcenter">
        <div class="pull-left">
          <div style="height:3em">
          <% if user_signed_in? %> Welcome <%= current_user.name %><br>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
          <% end %>
        </div>
        </div>
      </div><!--

      --><div class="col-lg-6 vcenter">
        <div class="banner">
          <div class="vcenter-2">
          NCS / Les Schwab Tires Wrestling Championships
         <h3>Presented by Farmers</h3>
          Feb 27-28, 2015
        </div>
        </div>
      </div><!--

      --><div class="col-lg-4 vcenter">
        <div class="pull-right">
          <div style="height:3em">
          <%= link_to "Home ",       root_path %>
          <% if user_signed_in? == false %>/
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">ADMIN<span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "ADD LEAGUE(user)", new_user_path %></li>
                  <li><%= link_to "VIEW LEAGUES / USERS", users_path %></li>
                  <li><%= link_to "VIEW ALL WRESTLERS", wrestlers_path %></li>
                </ul>
              </div>

              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">VIEW LEAGUE ENTRIES<span class="caret"></span></button>
                <ul class="dropdown-menu scrollable-menu" role="menu">
                  <% @users.each do |user| %>
                    <div style="width: 300px;">
                      <% if user.league != "" %>
                        <li><%= link_to "#{user.league} (#{user.wrestlers.count})", user_wrestlers_path(user) %></li>
                      <% end %>
                    </div>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <% if !current_user.admin? %>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  TOURNAMENT ENTRIES <span class="caret"></span>
                </button>
                <ul class="dropdown-menu scrollable-menu" role="menu">
                  <% if current_user.admin? || current_user.league != "" %>
                    <li><%= link_to "ENTER MY LEAGUE", user_wrestlers_path(current_user) %></li>
                  <% end %>
                  <li><%= link_to "VIEW OTHER LEAGUES", users_path %></li>
                  <li><%= link_to "VIEW ALL WRESTLERS", wrestlers_path %></li>
                  <li class="divider"></li>
                </ul>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<nav class="navbar navbar-default navbar-fixed-top visible-xs visible-sm" role="navigation">
  <div class="container">

    <div class="col-xs-12 vcenter">
      <div class="banner">
        <div class="vcenter-3">
          NCS / Les Schwab Tires Wrestling Championships - Presented by Farmers
        </div>
        </div>
      </div>
    <div class="row">
      <div class="col-xs-4 vcenter">
        <div class="pull-left">
          <div style="height:2em">
          <% if user_signed_in? %> Welcome <%= current_user.name %><br>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
          <% end %>
        </div>
        </div>
      </div><!--

   --><div class="col-xs-8 vcenter">
        <div class="pull-right">
          <div style="height:2em">
          <%= link_to "Home ",       root_path %>
          <% if user_signed_in? == false %>/
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">ADMIN<span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "ADD (user)", new_user_path %></li>
                  <li><%= link_to "VIEW LEAGUES", users_path %></li>
                  <li><%= link_to "VIEW WRESTLERS", wrestlers_path %></li>
                </ul>
              </div>

              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">LEAGUES<span class="caret"></span></button>
                <ul class="dropdown-menu scrollable-menu" role="menu">
                  <% @users.each do |user| %>
                    <div style="width: 300px;">
                      <% if user.league != "" %>
                        <li><%= link_to "#{user.league} (#{user.wrestlers.count})", user_wrestlers_path(user) %></li>
                      <% end %>
                    </div>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <% if !current_user.admin? %>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  ENTRIES <span class="caret"></span>
                </button>
                <ul class="dropdown-menu scrollable-menu" role="menu">
                  <% if current_user.admin? || current_user.league != "" %>
                    <li><%= link_to "MY LEAGUE", user_wrestlers_path(current_user) %></li>
                  <% end %>
                  <li><%= link_to "LEAGUES", users_path %></li>
                  <li><%= link_to "WRESTLERS", wrestlers_path %></li>
                  <li class="divider"></li>
                </ul>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_table_row.html.erb
<tr>
  <td><%= team.name %></td>
  <td><%= team.section %></td>
  <td><%= team.coach %></td>
  <% if current_user.admin? %>
    <td><%= team.cell %></td>
  <% end %>
    <td><%= link_to 'View Team', team_wrestlers_path(team)%></td>
    <td><%= link_to 'View Tournaments', team_tournaments_path(team)%></td>
  <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_team_path(team)%></td>
    <td><%= link_to 'Delete', team, method: "delete", :data => {:confirm => 'Are you sure? By deleting teams, all wrestlers associated with that team will also be deleted!'} %></td>
  <% end %>
  </td>
</tr>